id: PCACE663C
initial_creation_type: ocr
source_metadata:
  volumes:
    92c65b0777214289bae0756b5531d4d5:
      base_file: v057.txt
      image_group_id: I1PD95902
      title: འཁྲུལ་པ་བཟློག་པའི་རིགས་པ་གཏན་ཚིགས་གྲུབ་པ།
      total_pages: 1605
      volume_number: 57
